# permissions for end users to edit puppetcaissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: puppetcaissuer-editor-role
rules:
- apiGroups:
  - certmanager.puppetca
  resources:
  - puppetcaissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.puppetca
  resources:
  - puppetcaissuers/status
  verbs:
  - get
