// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetCAIssuer) DeepCopyInto(out *PuppetCAIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetCAIssuer.
func (in *PuppetCAIssuer) DeepCopy() *PuppetCAIssuer {
	if in == nil {
		return nil
	}
	out := new(PuppetCAIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PuppetCAIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetCAIssuerList) DeepCopyInto(out *PuppetCAIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PuppetCAIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetCAIssuerList.
func (in *PuppetCAIssuerList) DeepCopy() *PuppetCAIssuerList {
	if in == nil {
		return nil
	}
	out := new(PuppetCAIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PuppetCAIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetCAIssuerSpec) DeepCopyInto(out *PuppetCAIssuerSpec) {
	*out = *in
	out.Provisioner = in.Provisioner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetCAIssuerSpec.
func (in *PuppetCAIssuerSpec) DeepCopy() *PuppetCAIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(PuppetCAIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetCAIssuerStatus) DeepCopyInto(out *PuppetCAIssuerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetCAIssuerStatus.
func (in *PuppetCAIssuerStatus) DeepCopy() *PuppetCAIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(PuppetCAIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetCAProvisioner) DeepCopyInto(out *PuppetCAProvisioner) {
	*out = *in
	out.URL = in.URL
	out.Cert = in.Cert
	out.Key = in.Key
	out.CaCert = in.CaCert
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetCAProvisioner.
func (in *PuppetCAProvisioner) DeepCopy() *PuppetCAProvisioner {
	if in == nil {
		return nil
	}
	out := new(PuppetCAProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}
